version: "3"

networks:
  neofelis:

services:
  backend:
    networks:
      - neofelis
    container_name: neofelis-backend
    image: neofelis-backend
    restart: always
    build:
      context: .
    env_file: ./.env
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    ports:
      - "10080:8080"
